CREATE TABLE financial_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    change_1m DECIMAL(10, 2),
    volume_1m BIGINT,
    change_15m DECIMAL(10, 2),
    volume_15m BIGINT,
    change_1h DECIMAL(10, 2),
    volume_1h BIGINT,
    change_4h DECIMAL(10, 2),
    volume_4h BIGINT,
    change_12h DECIMAL(10, 2),
    volume_12h BIGINT,
    change_24h DECIMAL(10, 2),
    volume_24h BIGINT,
    change_3d DECIMAL(10, 2),
    volume_3d BIGINT,
    change_1w DECIMAL(10, 2),
    volume_1w BIGINT,
    change_2w DECIMAL(10, 2),
    volume_2w BIGINT,
    change_1month DECIMAL(10, 2),
    volume_1month BIGINT,
    change_3M DECIMAL(10, 2),
    volume_3M BIGINT,
    change_6M DECIMAL(10, 2),
    volume_6M BIGINT,
    change_1Y DECIMAL(10, 2),
    volume_1Y BIGINT,
    change_2Y DECIMAL(10, 2),
    volume_2Y BIGINT,
    change_5Y DECIMAL(10, 2),
    volume_5Y BIGINT,
    change_Total DECIMAL(10, 2),
    volume_Total BIGINT
);
